"""updated pets table

Revision ID: 01216db37863
Revises: aa8ce2b45c0c
Create Date: 2023-05-11 10:49:01.446088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01216db37863'
down_revision = 'aa8ce2b45c0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
