"""updated shelters table

Revision ID: aa8ce2b45c0c
Revises: bda74bca8c7e
Create Date: 2023-05-11 10:44:31.138136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa8ce2b45c0c'
down_revision = 'bda74bca8c7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shelters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shelters', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
